CREATE TABLE IF NOT EXISTS personagens (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    raca VARCHAR(50) NOT NULL,
    classe VARCHAR(50) NOT NULL,
    idade DATE NOT NULL,
    origem VARCHAR(100) NOT NULL,
    alinhamento VARCHAR(50) NOT NULL,
    forca INT NOT NULL,
    velocidade INT NOT NULL,
    agilidade INT NOT NULL,
    resistencia INT NOT NULL,
    inteligencia INT NOT NULL,
    sorte INT NOT NULL,
    tituloHistoria VARCHAR(150),
    historia VARCHAR(2000),
    genero VARCHAR(50) NOT NULL
    );