CREATE TABLE IF NOT EXISTS personagens (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    raca VARCHAR(50) NOT NULL,
    idade DATE NOT NULL,
    origem VARCHAR(100) NOT NULL,
    alinhamento VARCHAR(50) NOT NULL,
    forca INT NOT NULL,
    velocidade INT NOT NULL,
    agilidade INT NOT NULL,
    resistencia INT NOT NULL,
    inteligencia INT NOT NULL,
    sorte INT NOT NULL,
    tituloHistoria VARCHAR(150),
    historia VARCHAR(2000),
    genero VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS classes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
    );

INSERT INTO classes (nome) VALUES ('Guerreiro');
INSERT INTO classes (nome) VALUES ('Mago');
INSERT INTO classes (nome) VALUES ('Arqueiro');
INSERT INTO classes (nome) VALUES ('Ladino');

CREATE TABLE IF NOT EXISTS personagem_classe (
    personagem_id INT NOT NULL,
    classe_id INT NOT NULL,
    PRIMARY KEY (personagem_id, classe_id),
    FOREIGN KEY (personagem_id) REFERENCES personagens(id),
    FOREIGN KEY (classe_id) REFERENCES classes(id)
    );